// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for MessageCreatedEventType.
const (
	MessageCreatedEventTypeMessageCreated MessageCreatedEventType = "MessageCreated"
)

// Valid indicates whether the value is a known member of the MessageCreatedEventType enum.
func (e MessageCreatedEventType) Valid() bool {
	switch e {
	case MessageCreatedEventTypeMessageCreated:
		return true
	default:
		return false
	}
}

// Defines values for MessageDeletedEventType.
const (
	MessageDeletedEventTypeMessageDeleted MessageDeletedEventType = "MessageDeleted"
)

// Valid indicates whether the value is a known member of the MessageDeletedEventType enum.
func (e MessageDeletedEventType) Valid() bool {
	switch e {
	case MessageDeletedEventTypeMessageDeleted:
		return true
	default:
		return false
	}
}

// Defines values for MessageEditedEventType.
const (
	MessageEditedEventTypeMessageEdited MessageEditedEventType = "MessageEdited"
)

// Valid indicates whether the value is a known member of the MessageEditedEventType enum.
func (e MessageEditedEventType) Valid() bool {
	switch e {
	case MessageEditedEventTypeMessageEdited:
		return true
	default:
		return false
	}
}

// Defines values for StampImageReplacedEventType.
const (
	StampImageReplacedEventTypeStampImageReplaced StampImageReplacedEventType = "StampImageReplaced"
)

// Valid indicates whether the value is a known member of the StampImageReplacedEventType enum.
func (e StampImageReplacedEventType) Valid() bool {
	switch e {
	case StampImageReplacedEventTypeStampImageReplaced:
		return true
	default:
		return false
	}
}

// Defines values for StampInfoChangedEventType.
const (
	StampInfoChangedEventTypeStampInfoChanged StampInfoChangedEventType = "StampInfoChanged"
)

// Valid indicates whether the value is a known member of the StampInfoChangedEventType enum.
func (e StampInfoChangedEventType) Valid() bool {
	switch e {
	case StampInfoChangedEventTypeStampInfoChanged:
		return true
	default:
		return false
	}
}

// Defines values for StampUpdatedEventType.
const (
	StampUpdatedEventTypeStampUpdated StampUpdatedEventType = "StampUpdated"
)

// Valid indicates whether the value is a known member of the StampUpdatedEventType enum.
func (e StampUpdatedEventType) Valid() bool {
	switch e {
	case StampUpdatedEventTypeStampUpdated:
		return true
	default:
		return false
	}
}

// Defines values for UserIconReplacedEventType.
const (
	UserIconReplacedEventTypeUserIconReplaced UserIconReplacedEventType = "UserIconReplaced"
)

// Valid indicates whether the value is a known member of the UserIconReplacedEventType enum.
func (e UserIconReplacedEventType) Valid() bool {
	switch e {
	case UserIconReplacedEventTypeUserIconReplaced:
		return true
	default:
		return false
	}
}

// Defines values for UsernameChangedEventType.
const (
	UsernameChangedEventTypeUsernameChanged UsernameChangedEventType = "UsernameChanged"
)

// Valid indicates whether the value is a known member of the UsernameChangedEventType enum.
func (e UsernameChangedEventType) Valid() bool {
	switch e {
	case UsernameChangedEventTypeUsernameChanged:
		return true
	default:
		return false
	}
}

// Defines values for WebSocketEventType.
const (
	WebSocketEventTypeMessageCreated     WebSocketEventType = "MessageCreated"
	WebSocketEventTypeMessageDeleted     WebSocketEventType = "MessageDeleted"
	WebSocketEventTypeMessageEdited      WebSocketEventType = "MessageEdited"
	WebSocketEventTypeStampImageReplaced WebSocketEventType = "StampImageReplaced"
	WebSocketEventTypeStampInfoChanged   WebSocketEventType = "StampInfoChanged"
	WebSocketEventTypeStampUpdated       WebSocketEventType = "StampUpdated"
	WebSocketEventTypeUserIconReplaced   WebSocketEventType = "UserIconReplaced"
	WebSocketEventTypeUsernameChanged    WebSocketEventType = "UsernameChanged"
)

// Valid indicates whether the value is a known member of the WebSocketEventType enum.
func (e WebSocketEventType) Valid() bool {
	switch e {
	case WebSocketEventTypeMessageCreated:
		return true
	case WebSocketEventTypeMessageDeleted:
		return true
	case WebSocketEventTypeMessageEdited:
		return true
	case WebSocketEventTypeStampImageReplaced:
		return true
	case WebSocketEventTypeStampInfoChanged:
		return true
	case WebSocketEventTypeStampUpdated:
		return true
	case WebSocketEventTypeUserIconReplaced:
		return true
	case WebSocketEventTypeUsernameChanged:
		return true
	default:
		return false
	}
}

// Count 自然数
type Count = int

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// MessageCreatedBody defines model for MessageCreatedBody.
type MessageCreatedBody struct {
	// MessageCount 自然数
	MessageCount Count `json:"messageCount"`
}

// MessageCreatedEvent defines model for MessageCreatedEvent.
type MessageCreatedEvent struct {
	Body MessageCreatedBody      `json:"body"`
	Type MessageCreatedEventType `json:"type"`
}

// MessageCreatedEventType defines model for MessageCreatedEvent.Type.
type MessageCreatedEventType string

// MessageDeletedBody defines model for MessageDeletedBody.
type MessageDeletedBody struct {
	// MessageID UUID
	MessageID UUID `json:"messageId"`
}

// MessageDeletedEvent defines model for MessageDeletedEvent.
type MessageDeletedEvent struct {
	Body MessageDeletedBody      `json:"body"`
	Type MessageDeletedEventType `json:"type"`
}

// MessageDeletedEventType defines model for MessageDeletedEvent.Type.
type MessageDeletedEventType string

// MessageEditedBody defines model for MessageEditedBody.
type MessageEditedBody struct {
	MessageIds []UUID `json:"messageIds"`
}

// MessageEditedEvent defines model for MessageEditedEvent.
type MessageEditedEvent struct {
	Body MessageEditedBody      `json:"body"`
	Type MessageEditedEventType `json:"type"`
}

// MessageEditedEventType defines model for MessageEditedEvent.Type.
type MessageEditedEventType string

// OAuthResponse defines model for OAuthResponse.
type OAuthResponse struct {
	AccessToken  string  `json:"access_token"`
	ExpiresIn    int     `json:"expires_in"`
	RefreshToken *string `json:"refresh_token,omitempty"`

	// TokenType Example: Bearer
	TokenType string `json:"token_type"`
}

// SortByPopularity 人気 (True) / 最新 (False)
type SortByPopularity = bool

// Stamp defines model for Stamp.
type Stamp struct {
	// Count 自然数
	Count Count `json:"count"`

	// ID UUID
	ID UUID `json:"id"`
}

// StampImageReplacedBody defines model for StampImageReplacedBody.
type StampImageReplacedBody struct {
	// StampID UUID
	StampID UUID `json:"stampId"`
}

// StampImageReplacedEvent defines model for StampImageReplacedEvent.
type StampImageReplacedEvent struct {
	Body StampImageReplacedBody      `json:"body"`
	Type StampImageReplacedEventType `json:"type"`
}

// StampImageReplacedEventType defines model for StampImageReplacedEvent.Type.
type StampImageReplacedEventType string

// StampInfoChangedBody defines model for StampInfoChangedBody.
type StampInfoChangedBody struct {
	Name string `json:"name"`

	// StampID UUID
	StampID UUID `json:"stampId"`
}

// StampInfoChangedEvent defines model for StampInfoChangedEvent.
type StampInfoChangedEvent struct {
	Body StampInfoChangedBody      `json:"body"`
	Type StampInfoChangedEventType `json:"type"`
}

// StampInfoChangedEventType defines model for StampInfoChangedEvent.Type.
type StampInfoChangedEventType string

// StampUpdatedBody defines model for StampUpdatedBody.
type StampUpdatedBody struct {
	Stamps Stamps `json:"stamps"`
}

// StampUpdatedEvent defines model for StampUpdatedEvent.
type StampUpdatedEvent struct {
	Body StampUpdatedBody      `json:"body"`
	Type StampUpdatedEventType `json:"type"`
}

// StampUpdatedEventType defines model for StampUpdatedEvent.Type.
type StampUpdatedEventType string

// Stamps defines model for Stamps.
type Stamps struct {
	OthersCount *int    `json:"othersCount,omitempty"`
	Superior    []Stamp `json:"superior"`
}

// TimelineMessage defines model for TimelineMessage.
type TimelineMessage struct {
	Messages []UUID `json:"messages"`
}

// UUID UUID
type UUID = string

// User defines model for User.
type User struct {
	// ID UUID
	ID *UUID `json:"id,omitempty"`

	// Name ユーザー名
	Name *UserName `json:"name,omitempty"`

	// UserID ユーザーの ID
	UserID UserID `json:"userId"`
}

// UserIconReplacedBody defines model for UserIconReplacedBody.
type UserIconReplacedBody struct {
	// UserID ユーザーの ID
	UserID UserID `json:"userId"`
}

// UserIconReplacedEvent defines model for UserIconReplacedEvent.
type UserIconReplacedEvent struct {
	Body UserIconReplacedBody      `json:"body"`
	Type UserIconReplacedEventType `json:"type"`
}

// UserIconReplacedEventType defines model for UserIconReplacedEvent.Type.
type UserIconReplacedEventType string

// UserID ユーザーの ID
type UserID = string

// UserName ユーザー名
type UserName = string

// UserProfile defines model for UserProfile.
type UserProfile struct {
	// ID UUID
	ID *UUID `json:"id,omitempty"`

	// MessageCount 自然数
	MessageCount *Count `json:"messageCount,omitempty"`

	// Name ユーザー名
	Name *UserName `json:"name,omitempty"`

	// StampCount 自然数
	StampCount *Count `json:"stampCount,omitempty"`

	// UserID ユーザーの ID
	UserID UserID `json:"userId"`
}

// UserWebSocketEvent 送信される WebSocket イベント。
type UserWebSocketEvent struct {
	union json.RawMessage
}

// UsernameChangedBody defines model for UsernameChangedBody.
type UsernameChangedBody struct {
	User User `json:"user"`
}

// UsernameChangedEvent defines model for UsernameChangedEvent.
type UsernameChangedEvent struct {
	Body UsernameChangedBody      `json:"body"`
	Type UsernameChangedEventType `json:"type"`
}

// UsernameChangedEventType defines model for UsernameChangedEvent.Type.
type UsernameChangedEventType string

// WebSocketEventBase defines model for WebSocketEventBase.
type WebSocketEventBase struct {
	Body map[string]interface{} `json:"body"`
	Type WebSocketEventType     `json:"type"`
}

// WebSocketEventType defines model for WebSocketEventType.
type WebSocketEventType string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// OAuth defines model for OAuth.
type OAuth = OAuthResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PostAPIOauthTokenJSONBody defines parameters for PostAPIOauthToken.
type PostAPIOauthTokenJSONBody struct {
	Code *string `json:"code,omitempty"`
}

// GetTimelineParams defines parameters for GetTimeline.
type GetTimelineParams struct {
	SortByPopularity bool `form:"SortByPopularity" json:"SortByPopularity"`
}

// GetInParams defines parameters for GetIn.
type GetInParams struct {
	SortByPopularity bool `form:"SortByPopularity" json:"SortByPopularity"`
}

// PostAPIOauthTokenJSONRequestBody defines body for PostAPIOauthToken for application/json ContentType.
type PostAPIOauthTokenJSONRequestBody PostAPIOauthTokenJSONBody

// AsMessageCreatedEvent returns the union data inside the UserWebSocketEvent as a MessageCreatedEvent
func (t UserWebSocketEvent) AsMessageCreatedEvent() (MessageCreatedEvent, error) {
	var body MessageCreatedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageCreatedEvent overwrites any union data inside the UserWebSocketEvent as the provided MessageCreatedEvent
func (t *UserWebSocketEvent) FromMessageCreatedEvent(v MessageCreatedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageCreatedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided MessageCreatedEvent
func (t *UserWebSocketEvent) MergeMessageCreatedEvent(v MessageCreatedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageDeletedEvent returns the union data inside the UserWebSocketEvent as a MessageDeletedEvent
func (t UserWebSocketEvent) AsMessageDeletedEvent() (MessageDeletedEvent, error) {
	var body MessageDeletedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageDeletedEvent overwrites any union data inside the UserWebSocketEvent as the provided MessageDeletedEvent
func (t *UserWebSocketEvent) FromMessageDeletedEvent(v MessageDeletedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageDeletedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided MessageDeletedEvent
func (t *UserWebSocketEvent) MergeMessageDeletedEvent(v MessageDeletedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageEditedEvent returns the union data inside the UserWebSocketEvent as a MessageEditedEvent
func (t UserWebSocketEvent) AsMessageEditedEvent() (MessageEditedEvent, error) {
	var body MessageEditedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageEditedEvent overwrites any union data inside the UserWebSocketEvent as the provided MessageEditedEvent
func (t *UserWebSocketEvent) FromMessageEditedEvent(v MessageEditedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageEditedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided MessageEditedEvent
func (t *UserWebSocketEvent) MergeMessageEditedEvent(v MessageEditedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStampUpdatedEvent returns the union data inside the UserWebSocketEvent as a StampUpdatedEvent
func (t UserWebSocketEvent) AsStampUpdatedEvent() (StampUpdatedEvent, error) {
	var body StampUpdatedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStampUpdatedEvent overwrites any union data inside the UserWebSocketEvent as the provided StampUpdatedEvent
func (t *UserWebSocketEvent) FromStampUpdatedEvent(v StampUpdatedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStampUpdatedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided StampUpdatedEvent
func (t *UserWebSocketEvent) MergeStampUpdatedEvent(v StampUpdatedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUsernameChangedEvent returns the union data inside the UserWebSocketEvent as a UsernameChangedEvent
func (t UserWebSocketEvent) AsUsernameChangedEvent() (UsernameChangedEvent, error) {
	var body UsernameChangedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUsernameChangedEvent overwrites any union data inside the UserWebSocketEvent as the provided UsernameChangedEvent
func (t *UserWebSocketEvent) FromUsernameChangedEvent(v UsernameChangedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUsernameChangedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided UsernameChangedEvent
func (t *UserWebSocketEvent) MergeUsernameChangedEvent(v UsernameChangedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserIconReplacedEvent returns the union data inside the UserWebSocketEvent as a UserIconReplacedEvent
func (t UserWebSocketEvent) AsUserIconReplacedEvent() (UserIconReplacedEvent, error) {
	var body UserIconReplacedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserIconReplacedEvent overwrites any union data inside the UserWebSocketEvent as the provided UserIconReplacedEvent
func (t *UserWebSocketEvent) FromUserIconReplacedEvent(v UserIconReplacedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserIconReplacedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided UserIconReplacedEvent
func (t *UserWebSocketEvent) MergeUserIconReplacedEvent(v UserIconReplacedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStampInfoChangedEvent returns the union data inside the UserWebSocketEvent as a StampInfoChangedEvent
func (t UserWebSocketEvent) AsStampInfoChangedEvent() (StampInfoChangedEvent, error) {
	var body StampInfoChangedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStampInfoChangedEvent overwrites any union data inside the UserWebSocketEvent as the provided StampInfoChangedEvent
func (t *UserWebSocketEvent) FromStampInfoChangedEvent(v StampInfoChangedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStampInfoChangedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided StampInfoChangedEvent
func (t *UserWebSocketEvent) MergeStampInfoChangedEvent(v StampInfoChangedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStampImageReplacedEvent returns the union data inside the UserWebSocketEvent as a StampImageReplacedEvent
func (t UserWebSocketEvent) AsStampImageReplacedEvent() (StampImageReplacedEvent, error) {
	var body StampImageReplacedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStampImageReplacedEvent overwrites any union data inside the UserWebSocketEvent as the provided StampImageReplacedEvent
func (t *UserWebSocketEvent) FromStampImageReplacedEvent(v StampImageReplacedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStampImageReplacedEvent performs a merge with any union data inside the UserWebSocketEvent, using the provided StampImageReplacedEvent
func (t *UserWebSocketEvent) MergeStampImageReplacedEvent(v StampImageReplacedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UserWebSocketEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UserWebSocketEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
